<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EstadisticasJugadorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Limpiar tabla
        DB::table('estadisticas_jugador')->truncate();

        // Insertar estadísticas de ejemplo para todos los jugadores
        DB::table('estadisticas_jugador')->insert([
            [
                'jugador_id' => 49,
                'tiros_2_anotados' => 120,
                'tiros_2_fallidos' => 45,
                'tiros_3_anotados' => 60,
                'tiros_3_fallidos' => 80,
                'tiros_libres_anotados' => 50,
                'tiros_libres_fallidos' => 20,
                'rebotes_ofensivos' => 30,
                'rebotes_defensivos' => 150,
                'faltas_personales' => 25,
                'perdidas' => 40,
                'robos' => 20,
                'pts_partido' => 12.0,
                'rebotes_partido' => 8.3,
                'asistencias_partido' => 3.5,
                'fg_porcentaje' => 54.0,
            ],
            [
                'jugador_id' => 50,
                'tiros_2_anotados' => 200,
                'tiros_2_fallidos' => 60,
                'tiros_3_anotados' => 90,
                'tiros_3_fallidos' => 100,
                'tiros_libres_anotados' => 80,
                'tiros_libres_fallidos' => 15,
                'rebotes_ofensivos' => 25,
                'rebotes_defensivos' => 120,
                'faltas_personales' => 30,
                'perdidas' => 50,
                'robos' => 25,
                'pts_partido' => 18.5,
                'rebotes_partido' => 5.2,
                'asistencias_partido' => 4.0,
                'fg_porcentaje' => 48.7,
            ],
            [
                'jugador_id' => 51,
                'tiros_2_anotados' => 150,
                'tiros_2_fallidos' => 70,
                'tiros_3_anotados' => 80,
                'tiros_3_fallidos' => 90,
                'tiros_libres_anotados' => 60,
                'tiros_libres_fallidos' => 25,
                'rebotes_ofensivos' => 40,
                'rebotes_defensivos' => 160,
                'faltas_personales' => 20,
                'perdidas' => 35,
                'robos' => 30,
                'pts_partido' => 15.2,
                'rebotes_partido' => 7.8,
                'asistencias_partido' => 3.9,
                'fg_porcentaje' => 50.1,
            ],
            [
                'jugador_id' => 52,
                'tiros_2_anotados' => 180,
                'tiros_2_fallidos' => 50,
                'tiros_3_anotados' => 40,
                'tiros_3_fallidos' => 60,
                'tiros_libres_anotados' => 70,
                'tiros_libres_fallidos' => 10,
                'rebotes_ofensivos' => 50,
                'rebotes_defensivos' => 200,
                'faltas_personales' => 22,
                'perdidas' => 38,
                'robos' => 18,
                'pts_partido' => 16.8,
                'rebotes_partido' => 10.2,
                'asistencias_partido' => 2.5,
                'fg_porcentaje' => 52.0,
            ],
            [
                'jugador_id' => 53,
                'tiros_2_anotados' => 130,
                'tiros_2_fallidos' => 55,
                'tiros_3_anotados' => 85,
                'tiros_3_fallidos' => 70,
                'tiros_libres_anotados' => 60,
                'tiros_libres_fallidos' => 15,
                'rebotes_ofensivos' => 20,
                'rebotes_defensivos' => 110,
                'faltas_personales' => 18,
                'perdidas' => 28,
                'robos' => 22,
                'pts_partido' => 14.3,
                'rebotes_partido' => 4.9,
                'asistencias_partido' => 3.0,
                'fg_porcentaje' => 47.5,
            ],
            [
                'jugador_id' => 54,
                'tiros_2_anotados' => 90,
                'tiros_2_fallidos' => 40,
                'tiros_3_anotados' => 30,
                'tiros_3_fallidos' => 50,
                'tiros_libres_anotados' => 45,
                'tiros_libres_fallidos' => 12,
                'rebotes_ofensivos' => 15,
                'rebotes_defensivos' => 90,
                'faltas_personales' => 15,
                'perdidas' => 20,
                'robos' => 12,
                'pts_partido' => 10.5,
                'rebotes_partido' => 3.8,
                'asistencias_partido' => 2.1,
                'fg_porcentaje' => 44.0,
            ],
            [
                'jugador_id' => 55,
                'tiros_2_anotados' => 140,
                'tiros_2_fallidos' => 65,
                'tiros_3_anotados' => 50,
                'tiros_3_fallidos' => 60,
                'tiros_libres_anotados' => 55,
                'tiros_libres_fallidos' => 20,
                'rebotes_ofensivos' => 25,
                'rebotes_defensivos' => 130,
                'faltas_personales' => 24,
                'perdidas' => 32,
                'robos' => 20,
                'pts_partido' => 13.5,
                'rebotes_partido' => 6.2,
                'asistencias_partido' => 3.2,
                'fg_porcentaje' => 49.5,
            ],
            [
                'jugador_id' => 56,
                'tiros_2_anotados' => 110,
                'tiros_2_fallidos' => 45,
                'tiros_3_anotados' => 35,
                'tiros_3_fallidos' => 40,
                'tiros_libres_anotados' => 50,
                'tiros_libres_fallidos' => 18,
                'rebotes_ofensivos' => 30,
                'rebotes_defensivos' => 120,
                'faltas_personales' => 19,
                'perdidas' => 25,
                'robos' => 15,
                'pts_partido' => 11.2,
                'rebotes_partido' => 5.0,
                'asistencias_partido' => 2.8,
                'fg_porcentaje' => 46.0,
            ],
            [
                'jugador_id' => 57,
                'tiros_2_anotados' => 125,
                'tiros_2_fallidos' => 60,
                'tiros_3_anotados' => 55,
                'tiros_3_fallidos' => 65,
                'tiros_libres_anotados' => 60,
                'tiros_libres_fallidos' => 22,
                'rebotes_ofensivos' => 22,
                'rebotes_defensivos' => 115,
                'faltas_personales' => 20,
                'perdidas' => 30,
                'robos' => 18,
                'pts_partido' => 12.8,
                'rebotes_partido' => 5.5,
                'asistencias_partido' => 3.0,
                'fg_porcentaje' => 47.0,
            ],
            [
                'jugador_id' => 58,
                'tiros_2_anotados' => 100,
                'tiros_2_fallidos' => 55,
                'tiros_3_anotados' => 40,
                'tiros_3_fallidos' => 45,
                'tiros_libres_anotados' => 50,
                'tiros_libres_fallidos' => 18,
                'rebotes_ofensivos' => 18,
                'rebotes_defensivos' => 100,
                'faltas_personales' => 15,
                'perdidas' => 22,
                'robos' => 14,
                'pts_partido' => 10.0,
                'rebotes_partido' => 4.3,
                'asistencias_partido' => 2.5,
                'fg_porcentaje' => 45.5,
            ],
            [
                'jugador_id' => 59,
                'tiros_2_anotados' => 80,
                'tiros_2_fallidos' => 35,
                'tiros_3_anotados' => 25,
                'tiros_3_fallidos' => 30,
                'tiros_libres_anotados' => 20,
                'tiros_libres_fallidos' => 10,
                'rebotes_ofensivos' => 10,
                'rebotes_defensivos' => 90,
                'faltas_personales' => 12,
                'perdidas' => 18,
                'robos' => 10,
                'pts_partido' => 8.0,
                'rebotes_partido' => 5.5,
                'asistencias_partido' => 1.8,
                'fg_porcentaje' => 42.0,
            ],
            [
                'jugador_id' => 60,
                'tiros_2_anotados' => 70,
                'tiros_2_fallidos' => 25,
                'tiros_3_anotados' => 15,
                'tiros_3_fallidos' => 20,
                'tiros_libres_anotados' => 18,
                'tiros_libres_fallidos' => 5,
                'rebotes_ofensivos' => 12,
                'rebotes_defensivos' => 80,
                'faltas_personales' => 10,
                'perdidas' => 15,
                'robos' => 8,
                'pts_partido' => 7.5,
                'rebotes_partido' => 4.0,
                'asistencias_partido' => 1.5,
                'fg_porcentaje' => 43.5,
            ],
            [
                'jugador_id' => 64,
                'tiros_2_anotados' => 250,
                'tiros_2_fallidos' => 100,
                'tiros_3_anotados' => 300,
                'tiros_3_fallidos' => 150,
                'tiros_libres_anotados' => 200,
                'tiros_libres_fallidos' => 50,
                'rebotes_ofensivos' => 60,
                'rebotes_defensivos' => 250,
                'faltas_personales' => 40,
                'perdidas' => 80,
                'robos' => 60,
                'pts_partido' => 28.5,
                'rebotes_partido' => 8.3,
                'asistencias_partido' => 7.2,
                'fg_porcentaje' => 54.0,
            ],
        ]);
    }
}
