<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EstadisticasEquipoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        DB::table('estadisticas_equipo')->truncate();

        DB::table('estadisticas_equipo')->insert([
            [
                'equipo_id' => 1,
                'partido_id' => 1,
                'tiros_2_anotados' => 25,
                'tiros_2_fallidos' => 18,
                'tiros_3_anotados' => 8,
                'tiros_3_fallidos' => 14,
                'tiros_libres_anotados' => 12,
                'tiros_libres_fallidos' => 4,
                'rebotes_ofensivos' => 9,
                'rebotes_defensivos' => 22,
                'faltas_personales' => 18,
                'perdidas' => 11,
                'robos' => 6,
                'victorias' => 14,
                'derrotas' => 21,
            ],
            [
                'equipo_id' => 2,
                'partido_id' => 1,
                'tiros_2_anotados' => 28,
                'tiros_2_fallidos' => 15,
                'tiros_3_anotados' => 10,
                'tiros_3_fallidos' => 12,
                'tiros_libres_anotados' => 15,
                'tiros_libres_fallidos' => 3,
                'rebotes_ofensivos' => 11,
                'rebotes_defensivos' => 25,
                'faltas_personales' => 16,
                'perdidas' => 10,
                'robos' => 8,
                'victorias' => 15,
                'derrotas' => 19,
            ],
            [
                'equipo_id' => 3,
                'partido_id' => 1,
                'tiros_2_anotados' => 30,
                'tiros_2_fallidos' => 14,
                'tiros_3_anotados' => 12,
                'tiros_3_fallidos' => 10,
                'tiros_libres_anotados' => 18,
                'tiros_libres_fallidos' => 2,
                'rebotes_ofensivos' => 10,
                'rebotes_defensivos' => 28,
                'faltas_personales' => 15,
                'perdidas' => 9,
                'robos' => 7,
                'victorias' => 18,
                'derrotas' => 11,
            ],
            [
                'equipo_id' => 4,
                'partido_id' => 1,
                'tiros_2_anotados' => 27,
                'tiros_2_fallidos' => 17,
                'tiros_3_anotados' => 9,
                'tiros_3_fallidos' => 13,
                'tiros_libres_anotados' => 14,
                'tiros_libres_fallidos' => 5,
                'rebotes_ofensivos' => 8,
                'rebotes_defensivos' => 23,
                'faltas_personales' => 19,
                'perdidas' => 12,
                'robos' => 5,
                'victorias' => 44,
                'derrotas' => 23,
            ],
            [
                'equipo_id' => 5,
                'partido_id' => 1,
                'tiros_2_anotados' => 26,
                'tiros_2_fallidos' => 19,
                'tiros_3_anotados' => 11,
                'tiros_3_fallidos' => 11,
                'tiros_libres_anotados' => 13,
                'tiros_libres_fallidos' => 4,
                'rebotes_ofensivos' => 12,
                'rebotes_defensivos' => 24,
                'faltas_personales' => 17,
                'perdidas' => 10,
                'robos' => 6,
                'victorias' => 14,
                'derrotas' => 21,
            ],
            [
                'equipo_id' => 6,
                'partido_id' => 1,
                'tiros_2_anotados' => 24,
                'tiros_2_fallidos' => 20,
                'tiros_3_anotados' => 7,
                'tiros_3_fallidos' => 15,
                'tiros_libres_anotados' => 10,
                'tiros_libres_fallidos' => 6,
                'rebotes_ofensivos' => 7,
                'rebotes_defensivos' => 21,
                'faltas_personales' => 20,
                'perdidas' => 13,
                'robos' => 4,
                'victorias' => 14,
                'derrotas' => 21,
            ],
            [
                'equipo_id' => 7,
                'partido_id' => 1,
                'tiros_2_anotados' => 29,
                'tiros_2_fallidos' => 16,
                'tiros_3_anotados' => 10,
                'tiros_3_fallidos' => 12,
                'tiros_libres_anotados' => 16,
                'tiros_libres_fallidos' => 3,
                'rebotes_ofensivos' => 10,
                'rebotes_defensivos' => 26,
                'faltas_personales' => 16,
                'perdidas' => 9,
                'robos' => 7,
                'victorias' => 21,
                'derrotas' => 14,
            ],
            [
                'equipo_id' => 8,
                'partido_id' => 1,
                'tiros_2_anotados' => 23,
                'tiros_2_fallidos' => 21,
                'tiros_3_anotados' => 8,
                'tiros_3_fallidos' => 14,
                'tiros_libres_anotados' => 11,
                'tiros_libres_fallidos' => 5,
                'rebotes_ofensivos' => 9,
                'rebotes_defensivos' => 22,
                'faltas_personales' => 18,
                'perdidas' => 14,
                'robos' => 5,
                'victorias' => 34,
                'derrotas' => 21,
            ],
            [
                'equipo_id' => 9,
                'partido_id' => 1,
                'tiros_2_anotados' => 28,
                'tiros_2_fallidos' => 17,
                'tiros_3_anotados' => 9,
                'tiros_3_fallidos' => 13,
                'tiros_libres_anotados' => 14,
                'tiros_libres_fallidos' => 4,
                'rebotes_ofensivos' => 11,
                'rebotes_defensivos' => 24,
                'faltas_personales' => 17,
                'perdidas' => 11,
                'robos' => 6,
                'victorias' => 14,
                'derrotas' => 6,
            ],
            [
                'equipo_id' => 10,
                'partido_id' => 1,
                'tiros_2_anotados' => 26,
                'tiros_2_fallidos' => 18,
                'tiros_3_anotados' => 8,
                'tiros_3_fallidos' => 14,
                'tiros_libres_anotados' => 12,
                'tiros_libres_fallidos' => 5,
                'rebotes_ofensivos' => 10,
                'rebotes_defensivos' => 23,
                'faltas_personales' => 19,
                'perdidas' => 12,
                'robos' => 5,
                'victorias' => 14,
                'derrotas' => 5,
            ],
        ]);
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
